# Generated by Django 3.1.5 on 2021-04-08 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lycee', '0002_auto_20210317_0847'),
    ]

    operations = [
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=50)),
                ('isMissing', models.BooleanField(null=True)),
                ('date', models.DateField(default='AAAA-MM-DD')),
                ('start_time', models.TimeField(default='HH:MM:SS')),
                ('stop_time', models.TimeField(default='HH:MM:SS')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lycee.student')),
            ],
        ),
    ]
