# Generated by Django 3.1.5 on 2021-04-10 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lycee', '0003_absence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='absence',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='absence',
            name='stop_time',
        ),
    ]
