# Generated by Django 3.1.5 on 2021-04-10 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lycee', '0004_auto_20210410_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absence',
            name='reason',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
