# Generated by Django 3.1.5 on 2021-04-11 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lycee', '0005_auto_20210410_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='absence',
            name='cursus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lycee.cursus'),
        ),
    ]
